/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "serial.h"


#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void USART1_EXTI25_IRQHandler(void)
{

//	if ((USART1_PORT.UART->ISR & (USART_ISR_ORE | USART_ISR_FE)) != 0)) {
		// set the flags ORECF and FECF to 1
//		USART1_PORT->UART->ICR = serial_port->UART->ICR | (1 << 3 | 1 << 1);
//	}
	//else {
		read_into_kernel();
	//}
	//terminating_char_sent = SerialReadChar(incoming_buffer, &USART1_PORT);
	EXTI->PR |= EXTI_PR_PR0;
}




void finished_transmission(uint32_t bytes_sent) {
	// This function will be called after a transmission is complete

	volatile uint32_t test = 0;
	// make a very simple delay
	for (volatile uint32_t i = 0; i < 0x8ffff; i++) {
		// waste time !
	}
}


void enable_clocks() {

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOEEN;

}

int main(void)
{

	//Enable
	enable_clocks();

	void (*completion_function)(uint32_t) = &LED_string;

	//LED_string(4, (string_to_send + 4));

	SerialInitialise(BAUD_115200, &USART1_PORT, completion_function);
	initialise_board();

	NVIC_EnableIRQ(USART1_IRQn);


	/* Loop forever */
	for(;;) {

		//Initialise relevant memory
	 	uint8_t *operator = (uint8_t*) malloc(100 * sizeof(uint8_t));
		uint8_t operator_length = 0;
		uint8_t *operand = (uint8_t*) malloc(100 * sizeof(uint8_t));
		uint8_t operand_length = 0;

		Get_Command(operator, operator_length, operand, operand_length);
		//operator = (int *)realloc(operator, sizeof(int)*3);

	// to use string compare you need to set the end of the strings to the null terminating character

		if(strcmp("led", operator) == 0){
			//This is component or question 1
		}

		else if(strcmp(operator, "serial") == 0){
			uint8_t banana = 'get in';
			SerialOutputString(operand, &USART1_PORT);
		}

		else if(strcmp(operator, "oneshot") == 0){
			//This is the advanced section of the timer part
		}

		else if(strcmp(operator, "timer") == 0){
			//I think this is the second section for the timer

		}

		else{
			//Have the LEDs flashing
			uint8_t banana = 'get int';
		}

		free(operator);
		free(operand);
	}

}



