/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "serial.h"
#include "movement.h"


#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void (*on_button_press)() = 0x00;

void USART1_IRQnHandler(void)
{

	if (on_button_press != 0x00) {
		on_button_press();
	}


	volatile uint8_t *incoming_buffer[200];
	SerialReadString(incoming_buffer, USART1);
	//Is this correct or does it still use too much polling for characters


	// reset the interrupt (so it doesn't keep firing until the next trigger)
	EXTI->PR |= EXTI_PR_PR0;
}

void finished_transmission(uint32_t bytes_sent) {
	// This function will be called after a transmission is complete

	volatile uint32_t test = 0;
	// make a very simple delay
	for (volatile uint32_t i = 0; i < 0x8ffff; i++) {
		// waste time !
	}
}


void enable_clocks() {

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOEEN;

}

int main(void)
{

	uint8_t *string_to_send = "This is a string !\r\n";
	enable_clocks();

	void (*completion_function)(uint32_t) = &LED_string;

	//LED_string(4, (string_to_send + 4));


	SerialInitialise(BAUD_115200, &USART1_PORT, completion_function);
	initialise_board();

	on_button_press = &chase_led;
	enable_interrupt();



	/* Loop forever */
	for(;;) {

	}
}
