/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "serial.h"


#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void USART1_EXTI25_IRQHandler(void)
{

//	if ((USART1_PORT.UART->ISR & (USART_ISR_ORE | USART_ISR_FE)) != 0)) {
		// set the flags ORECF and FECF to 1
//		USART1_PORT->UART->ICR = serial_port->UART->ICR | (1 << 3 | 1 << 1);
//	}
	//else {
		read_into_kernel();
	//}
	//terminating_char_sent = SerialReadChar(incoming_buffer, &USART1_PORT);
	EXTI->PR |= EXTI_PR_PR0;
}




void finished_transmission(uint32_t bytes_sent) {
	// This function will be called after a transmission is complete

	volatile uint32_t test = 0;
	// make a very simple delay
	for (volatile uint32_t i = 0; i < 0x8ffff; i++) {
		// waste time !
	}
}


void enable_clocks() {

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOEEN;

}

int main(void)
{

	uint8_t received_string[200];
	uint8_t current_string_length = 0;

	enable_clocks();

	void (*completion_function)(uint32_t) = &LED_string;

	//LED_string(4, (string_to_send + 4));

	SerialInitialise(BAUD_115200, &USART1_PORT, completion_function);
	initialise_board();

	NVIC_EnableIRQ(USART1_IRQn);


	/* Loop forever */
	for(;;) {
		current_string_length = Receive_Data(received_string, current_string_length);


	}
}



