/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "serial.h"

// IVE EDITED THE CODE


#include "stm32f303xc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




int main(void)
{
	volatile uint8_t *incoming_buffer[200];
	enable_clocks();
	void (*completion_function)(uint32_t) = &LED_string;

	SerialInitialise(BAUD_115200, &USART1_PORT, completion_function);
	initialise_board();

	SerialReadString(incoming_buffer, &USART1_PORT);



	/* Loop forever */
	for(;;) {
	}
}
